
services:
  db:
    image: postgres:16.2
    restart: always
    container_name: cards-mvp-db
    user: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      # - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=cards-mvp
      - POSTGRES_PASSWORD=password
    volumes:
      # - ./db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.0.15
    restart: always
    container_name: cards-mvp-redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
  # redisinsight:
  #   image: redislabs/redisinsight:latest
  #   restart: always
  #   depends_on:
  #     - redis
  #   container_name: cards-mvp-redisinsight
  #   ports:
  #     - 8001:8001
  #   volumes:
  #     - ./redisinsight-data:/usr/src/app/data 
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379

volumes:
  db-data:
  redis-data:
  # redisinsight-data: