name: CI

on:
  push: 
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"

jobs:
  test-api-happy-path:
    runs-on: ubuntu-latest
    name: Integration Test (happy path)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
            version: 9.0.6
            run_install: false

      - name: Install Node 20.x
        uses: actions/setup-node@v4
        with:
            node-version: "20.x"
            cache: pnpm

      - name: Install Dependencies
        run: pnpm install && pnpm --filter apispec install

      - name: Start App Container
        run: |
          docker compose up -d
          CONTAINER_NAME=eon-rpg-dev-server  # Replace with your service name
          CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_NAME)
          echo "CONTAINER_IP=$CONTAINER_IP" >> $GITHUB_ENV

      - name: Run API Tests
        run: |
          cd api/spec
          npx stepci run workflow.yml --env host=${{env.CONTAINER_IP}}:8889

      - name: Stop App Container
        run: docker compose down
        if: always()

